exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
decoration {
    blur {
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
        noise = 0.02
        contrast = 1.0
        brightness = 1.0
     }
}

#layerrule = unset, waybar
